name: Build JavaScript assets

on:
    push:
        branches:
            - master
            - beta13

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - uses: flarum/action-build@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
